In [1]:
import numpy as np

In [ ]:
list_1 = [1,2,3,4,5,6,7,8,9]
summation = 0
for item in list_1:
    summation = summation + item # summation += summation: shorter version
summation 

In [ ]:
# For the trajectory of summation via "append"
summation_trajectory = []
summation_2 = 0
for item in list_1:
    summation_2 = summation_2 + item
    summation_trajectory.append(summation_2)
summation_trajectory

In [ ]:
# For the trajectory of summation via "numpy.zeros assigment and range"
summation_nump = np.zeros(9) # np.zeros(len(list_1)) better!
summation_3 = 0
for i in range(9):
    summation_3 = summation_3 + list_1[i]
    summation_nump[i] = summation_3
summation_nump

In [ ]:
# For the trajectory of summation via "list assignment and range"
summation_nump2 = [0] * len(list_1)
summation_32 = 0
for i in range(9):
    summation_32 = summation_32 + list_1[i]
    summation_nump2[i] = summation_32
summation_nump2

In [ ]:
# For the trajectory of summation via "enumerate"
summation_list = range(len(list_1))
summation_4 = 0
for i,item in enumerate(list_1):
    summation_4 = summation_4 + list_1[i]
    summation_list[i] = summation_4
summation_list

In [ ]:
# For the trajectory of summation via "enumerate"
summation_list = [0] * len(list_1)
summation_4 = 0
for i,item in enumerate(list_1):
    summation_4 = summation_4 + list_1[i]
    summation_list[i] = summation_4
summation_list

In [ ]:
# For the trajectory of summation via "enumerate"
summation_list2 = [0] * len(list_1)
summation_5 = 0
for i,item in enumerate(list_1):
    summation_5 = summation_5 + item
    summation_list2[i] = summation_5
summation_list2

> HOLA! Notice the difference Beri,beri, beriii..

In [ ]:
# Arithmetic mean of consecutive elements in a list via "enumerate"
a = range(12)
b = []
for i, k in enumerate(a[1:]):
    b.append((a[i] + a[i+1])/2) 
b


In [ ]:
# Arithmetic mean of consecutive elements in a list via "numpy array assignment"
a1 = range(12)
b1 = np.zeros(len(range(12))-1) # len(a)
for i in range(len(b1)):
    b1[i]=(a1[i]+a1[i+1])/2
b1

In [ ]:
# Arithmetic mean of consecutive elements in a list via "list assignment"
a2 = range(12)
b2 = [0] * (len(range(12))-1) # len(a)
for i in range(len(b2)):
    b2[i]=(a2[i]+a2[i+1])/2
b2

In [ ]:
# Arithmetic mean of consecutive elements in a list via "list comprehension"
a3 = range(12)
comp_list = [(a3[i] + a3[i+1])/2 for i in range(12)]
comp_list

In [ ]:
# Arithmetic mean of consecutive elements in a list via "list comprehension"
a3 = range(12)
comp_list = [(a3[i] + a3[i+1])/2 for i in range(11)]
comp_list

In [ ]:
# Arithmetic mean of consecutive elements in a list via "list comprehension and enumerate(unnecessary)"
a3 = range(12)
comp_list = [(a3[i] + a3[i+1])/2 for i, item in enumerate(a3[1:])]
comp_list

> Can we implement the summation trajectory via list comprehensions?

## Training

In [ ]:
# Squaring of each element in a list via?
numbers = [1,3,5,7,9]
squares = []
for number in numbers:
    squares.append(number**2)
squares

In [ ]:
# Squaring of each element in a list via?
numbers = [1,3,5,7,9]
squares = np.zeros(len(numbers))
for p in range(len(numbers)):
    squares[p] = numbers[p]**2
squares

In [ ]:
# Squaring of each element in a list via?
numbers = [1,3,5,7,9]
squares = [0] * len(numbers)
for z in range(len(numbers)):
    squares[z] = numbers[z]**2
squares

In [ ]:
# Squaring of each element in a list via?
numbers = [1,6,16,26,36]
squares = [0] * len(numbers)
for i, number in enumerate(numbers):
    squares[i] = number**2
squares

In [ ]:
# Squaring of each element in a list via?
numbers = [1,6,16,26,36]
squares = [0] * len(numbers)
for i, number in enumerate(numbers):
    squares[i] = numbers[i]**2
squares

Let's Comprehense

In [ ]:
# Squaring of each element in a list via?
numbers = [1,3,5,7,9]
squares = [number**2 for number in numbers]
squares

<b> Structure of Comprehension
<n>
[ <font color=blue>(expression) <font color=green>for (item or index or dummy variable) <font color=green>in (ordered object) ]

In [ ]:
[c for c in "Madiyim mi seni Beri"]

In [ ]:
[ x+y for x,y in [(1,2), (2,-1), (4,2), (3,7)] ]

In [ ]:
# Function with a comprehension
def summ(a,b):
    return a+b

[summ(x,y) for x,y in [(1,2), (2,-1), (4,2), (3,7)] ]

In [ ]:
# Function with a comprehension
def square(x):
    squares = [number**2 for number in x]
    return squares
square([1,2,3,4,5,6])

### Let's add some condition(al)s

In [ ]:
numbers = [1,3,5,7,9,11]
squares = []
for number in numbers:
    if number > 4:
        squares.append(number**2)
squares

In [ ]:
# With comprehension
[x**2 for x in numbers if x > 4]

In [ ]:
# With comprehension
[Beri**2 for Beri in numbers if Beri > 4]

In [ ]:
# If we want to apply another operation when the condition is violated:
numbers = [2,5,7,9,13,15,17,21]
[ lulu**3 if lulu > 10 else lulu for lulu in numbers]

In [ ]:
# For loop implementation of above code
numbers = [2,5,7,9,13,15,17,21]
listo = []
for lulu in numbers:
    if lulu > 10:
        listo.append(lulu**3)
    else:
        listo.append(lulu)
listo

### Nested Loops

In [ ]:
# Nested Loops
# Flattening the list of lists
list_of_lists = [[1,2,3], [4,5,6], [7,8,9]]
flatten_list = []
for sublist in list_of_lists:
    for element in sublist:
        flatten_list.append(element)
flatten_list

In [ ]:
list_of_lists

In [ ]:
# Comprehensed version
flattened = [element for sublist in list_of_lists for element in sublist]
flattened

In [ ]:
# or
flatten = [x for y in list_of_lists for x in y]
flatten

In [ ]:
# Pairing letter list's elements and number list's elements
pair_list = []
for letter in "Ölücem":
    for number in [1,2,3,4,5]:
        pair_list.append((letter,number))
pair_list

In [ ]:
# If we want one to one pairing: We have "zip" for this purpose
letters = "TabiCanım"
numbers = [1,3,5,7,9,11,13,17,23]
for letter, number in zip(letters, numbers):
    print((letter, number))


In [ ]:
# Enumerate investigation
letters = "TabiCanım"
for i, letter in enumerate(letters):
    print(i,letter)

In [ ]:
# Enumerate investigation
letters = "TabiCanım"
for i, letter in enumerate(letters):
    print((i,letter))

### Çerez Niyetine

In [ ]:
# Prime detector
x = 97
k = 0
for i in range(2,x):
    if x%i == 0:
        k = k+1
if k >=1:
    print("%d is not prime" % x)
else:
    print("%d is a prime number!" % x)


In [ ]:
x=17 
not np.any([x%i == 0 for i in range(2, x)])

In [ ]:
x=18 
not np.any([x%i == 0 for i in range(2, x)])

### ii-) Another approach

In [91]:
n = 24
is_prime = True
for i in range(2,n):
    if n%i == 0:
        is_prime = False
print(is_prime)

False


In [97]:
# What about comprehensed version?
[n%i == 0 for i in range(2,n)] # brick 1

[True,
 True,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False]

In [98]:
np.any([n%i == 0 for i in range(2,n)]) # brick 2

True

In [99]:
not np.any([n%i == 0 for i in range(2,n)]) # birck 3(last)

False

In [101]:
not(np.any([n%i == 0 for i in range(2,n)])) # identical little girl/boy-boy/girl

False

## Detecting the differences between two lists

In [3]:
mesut1 = [1,2,3,4,5,6,7,8,9]
mesut2 = [1,2,4,4,5,5,6,6,7]
index_list = []
for x,y in zip(mesut1,mesut2):
    if x!=y:
        index_list.append(mesut1.index(x))
index_list

[2, 5, 6, 7, 8]

In [4]:
len(mesut1)

9

In [5]:
[mesut1.index(x) for x,y in zip(mesut1,mesut2) if x!=y]

[2, 5, 6, 7, 8]

In [ ]:
len([mesut1.index(x) for x,y in zip(mesut1,mesut2) if x!=y])/len(mesut!) # percentage of differences

## Minimum Finder for a given list

In [2]:
a_list = [2,4,5,7, 11, 0,-1,-8]
max_0 = a_list[0]
for element in a_list:
    if element > max_0:
        max_0 = element
    else:
        max_0 = max_0
print(max_0)

11


In [4]:
# Can we implement this problem in comprehensed fashion?
# Let's try
max_0 = a_list[0]
[max_0 for element in a_list if element > max_0]

[2, 2, 2, 2]

In [8]:
#That is not what we want1

In [7]:
max_0 = a_list[0]
[element if element > max_0 else max_0 for element in a_list]

[2, 4, 5, 7, 11, 2, 2, 2]

In [ ]:
#That is not what we want2

In [9]:
max_0 = a_list[0]
[max_0 = element if element > max_0 = max_0 else max_0 for element in a_list]

SyntaxError: invalid syntax (<ipython-input-9-58c0e3c09798>, line 2)

In [10]:
# Hmmmmm... We cannot implement this problem with a comprehension.
#The reason is that comprehension methods are construction methods. List construction, set constuction, dictionary construction...

## Finding the "k" which is the desired number of eigenvalues for a certain compression loss(e.g. %95) when implementing the PCA on a raw data.

In [2]:
eig_list = [32, 30,25, 3, 2.8, 2.1, 1.73, 1.71, 0.68, 0.33, 0.11, 0.02]
for k in range(len(eig_list)):
    ratio = sum(eig_list[0:k+1])/ sum(eig_list)
    if  ratio >= 0.95:
        break
print(k+1)

6


In [9]:
for i,component in enumerate(eig_list):
    ratio = sum(eig_list[0:i+1])/ sum(eig_list)
    if  ratio >= 0.95:
        break
print(k+1)

6


In [14]:
for i,component in enumerate(eig_list):
    ratio = sum(eig_list[0:i+1])/ sum(eig_list)
    if  ratio >= 0.95:
        break
print(eig_list.index(component)+1)

6


In [3]:
eig_list = [32, 30,25, 3, 2.8, 2.1, 1.73, 1.71, 0.68, 0.33, 0.11, 0.02]
eig_list[0:0]

[]

In [4]:
eig_list = [32, 30,25, 3, 2.8, 2.1, 1.73, 1.71, 0.68, 0.33, 0.11, 0.02]
sum(eig_list[0:5])/sum(eig_list)

0.9328508242862887

In [5]:
len(eig_list), sum(eig_list[0:13])/sum(eig_list)

(12, 1.0)

In [6]:
# Numpy implementation
normalized_cumsum = np.cumsum(eig_list)/ sum(eig_list)
normalized_cumsum

array([ 0.3216727 ,  0.62324085,  0.87454765,  0.90470446,  0.93285082,
        0.9539606 ,  0.97135103,  0.98854041,  0.99537595,  0.9986932 ,
        0.99979895,  1.        ])

In [8]:
normalized_cumsum[(normalized_cumsum <= 0.95)]

array([ 0.3216727 ,  0.62324085,  0.87454765,  0.90470446,  0.93285082])

In [62]:
# That was like a MATLAB way
len(normalized_cumsum[(normalized_cumsum <= 0.95)])+1

6

In [63]:
# That was like a MATLAB way
len(normalized_cumsum[normalized_cumsum <= 0.95])+1

6

In [60]:
normalized_cumsum[(normalized_cumsum <= 0.95)].index

AttributeError: 'numpy.ndarray' object has no attribute 'index'

In [70]:
np.where(normalized_cumsum <= 0.95)

(array([0, 1, 2, 3, 4], dtype=int64),)

In [71]:
len(np.where(normalized_cumsum <= 0.95))

1

In [ ]:
# Something must be odd(abnormal, strange).

In [72]:
type(np.where(normalized_cumsum <= 0.95))

tuple

In [92]:
# Yeah! output type was a tuple!

In [93]:
np.where(normalized_cumsum <= 0.95)[0]

array([0, 1, 2, 3, 4], dtype=int64)

In [75]:
len(np.where(normalized_cumsum <= 0.95)[0])

5

In [76]:
# The answer is:
len(np.where(normalized_cumsum <= 0.95)[0]) + 1

6

In [17]:
(np.where(normalized_cumsum <= 0.95)[0]).max() + 2

6

## Multiplication of elements in a given list

In [81]:
g_list = [2,3,4,5,6,7,8,10]
prod = 1
for item in g_list:
    prod = prod*item
prod

40320

In [80]:
g_list = [2,3,4,5,6,7,8,10]
prod = 1
for item in g_list[:4]:
    prod = prod*item
prod

120

In [83]:
g_list = [2,3,4,5,6,7,8,10]
cumprod_list = []
prod = 1
for item in g_list:
    prod = prod*item
    cumprod_list.append(prod)
cumprod_list

[2, 6, 24, 120, 720, 5040, 40320]

In [87]:
g_list = [2,3,4,5,6,7,8,10]
cumprod_list = [0]*len(g_list)
prod = 1
for i in range(len(g_list)):
    prod = prod*g_list[i]
    cumprod_list[i] = prod
cumprod_list

[2, 6, 24, 120, 720, 5040, 40320]

In [88]:
g_list = [2,3,4,5,6,7,8,10]
cumprod_list = np.zeros(len(g_list))
prod = 1
for i in range(len(g_list)):
    prod = prod*g_list[i]
    cumprod_list[i] = prod
cumprod_list

array([  2.00000000e+00,   6.00000000e+00,   2.40000000e+01,
         1.20000000e+02,   7.20000000e+02,   5.04000000e+03,
         4.03200000e+04])

In [90]:
g_list = [2,3,4,5,6,7,8]
cumprod_list = [0]*len(g_list)
prod = 1
for i, element in enumerate(g_list):
    prod = prod*element
    cumprod_list[i] = prod
cumprod_list

[2, 6, 24, 120, 720, 5040, 40320]

In [ ]:
# Let's write factorial function

In [102]:
def factorial(n):
    if n == 0:
        return 1
    else:
        N = 1
        for i in range(1, n+1):
            N = N*i
    return(N)

In [103]:
benim_faktöryelim = factorial(25)
benim_faktöryelim

15511210043330985984000000

In [104]:
def factorial(n):
    if n == 0:
        return 1
    else:
        N = 1
        for i in range(2, n+1): # one step shorter, hihi
            N = N*i
    return(N)
seninki = factorial(22)
seninki

1124000727777607680000

## Flatten the matrix

In [119]:
mam = np.ones((28,28))
tt = [elements for rows in mam for elements in rows]
tt.shape

AttributeError: 'list' object has no attribute 'shape'

In [120]:
mam = np.ones((28,28))
tt = np.array([elements for rows in mam for elements in rows])
tt.shape

(784,)

In [121]:
mam = np.ones((28,28))
tt = np.asarray([elements for rows in mam for elements in rows])
tt.shape

(784,)

In [149]:
# Turn it into a function
def matrixflatter(M):
    M_flat = np.array([elements for rows in M for elements in rows])
    return M_flat
Z = np.matrix(np.ones((4,3)))
k = matrixflatter(Z)
k

array([[[ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.]]])

In [145]:
# Somethings got wrong. Let's check our function step by step(piece by piece)
Z

matrix([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])

In [146]:
[rows for rows in Z]

[matrix([[ 1.,  1.,  1.]]),
 matrix([[ 1.,  1.,  1.]]),
 matrix([[ 1.,  1.,  1.]]),
 matrix([[ 1.,  1.,  1.]])]

In [148]:
[elements for rows in Z for elements in rows]

[matrix([[ 1.,  1.,  1.]]),
 matrix([[ 1.,  1.,  1.]]),
 matrix([[ 1.,  1.,  1.]]),
 matrix([[ 1.,  1.,  1.]])]

In [150]:
# It is very strange.
np.array([elements for rows in Z for elements in rows])

array([[[ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.]]])

In [151]:
# I don't know the np.matrix structure. Let's transform it into an array
[elements for rows in np.array(Z) for elements in rows]

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

In [156]:
# Done! our new function:
def matrixflatter2(M):
    M_flattened = np.array([elements for rows in np.array(M) for elements in rows])
    return M_flattened
matrixflatter2(Z)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [131]:
# With pythonic methods
def matrixreshaper(u):
    u_reshape = np.array(u).flatten()
    return u_reshape
matrixreshaper(Z)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [125]:
# What is the difference between array() and asarray()???
A = np.matrix(np.ones((3,3)))
np.array(A)[2]=2
A

matrix([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])

In [127]:
# A-ha, it couldn't modify the matrix.
#Stackoverflow explanation: Doesn't work because you are modifying a copy.
np.asarray(A)[2]=2
A

matrix([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 2.,  2.,  2.]])

In [129]:
# Done!
A_reshaped = np.array(A).flatten()
A_reshaped

array([ 1.,  1.,  1.,  1.,  1.,  1.,  2.,  2.,  2.])

## Fibonacci

In [23]:
n = 3
a = 0
b = 1
for i in range(n):
    
    b = b + a
    a = b
print (b)


4


In [29]:
n = 20
a = 0
b = 1
c = 0
fib_list = []
fib_list.append(a)
fib_list.append(b)
for i in range(n):
    c = b + a
    a = b
    b = c
    fib_list.append(c)
print(fib_list)


[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946]


In [20]:
n = 3
a = 0
b = 1
for i in range(n):
    print (a)
    a = b
    b = b + a


0
1
2
